apiVersion: v1
kind: Service
metadata:
  name: account-svc
spec:
  type: NodePort
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 30006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: saikaranam/account-service:latest
          ports:
            - containerPort: 9080
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: root