apiVersion: v1
kind: Service
metadata:
  name: operation-svc
spec:
  type: NodePort
  selector:
    app: all-application-service
  ports:
    - protocol: TCP
      port: 9060
      targetPort: 9060
      nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-application-service-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: all-application-service
  template:
    metadata:
      labels:
        app: all-application-service
    spec:
      containers:
        - name: all-application-service
          image: saikaranam/all-application-service:latest
          ports:
            - containerPort: 9060
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: root