apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: saikaranam/customer-service:latest
          ports:
            - containerPort: 9090
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: root