apiVersion: v1
kind: Service
metadata:
  name: operation-svc
spec:
  type: NodePort
  selector:
    app: operation-service
  ports:
    - protocol: TCP
      port: 9070
      targetPort: 9070
      nodePort: 30004

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: operation-service-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: operation-service
  template:
    metadata:
      labels:
        app: operation-service
    spec:
      containers:
        - name: operation-service
          image: saikaranam/operation-service:latest
          ports:
            - containerPort: 9070
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: root