runtime: nodejs18

instance_class: F2

env_variables: 
  BUCKET_NAME: "simple-banking-app"

handlers:
- url: /
  static_files: dist/web-ui/index.html
  upload: dist/web-ui/index.html

- url: /
  static_dir: dist/web-ui