server:
  port: 9080
spring:
  profiles:
    active: dev
  application:
    name: account-service
  main:
    allow-bean-definition-overriding: true
#eureka:
  #client:
    #service-url:
      #default-zone: http://localhost:8761/eureka/